# -*- coding: utf-8 -*-
"""Copy of internship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cyZVdVhFElQc6wtyVhUBBC5lHGPDSpFQ
"""

# imports we need
import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive

# I've imported the new files in as csv files
# not sure we are doing that but can be changed

drive.flush_and_unmount()

drive.mount('/content/drive', force_remount=True)

enrollment = pd.read_csv("/content/drive/MyDrive/MadridIntern/clean_enrollment.csv")
teacher = pd.read_csv("/content/drive/MyDrive/MadridIntern/clean_availability.csv")
periods = pd.read_csv("/content/drive/MyDrive/MadridIntern/clean_periods.csv")
counts = pd.read_csv("/content/drive/MyDrive/MadridIntern/clean_counts.csv")

#Test the Headers
print(enrollment.head())
print(teacher.head())
print(periods.head())

#Test the Column Names
print(enrollment.columns)
print(teacher.columns)
print(periods.columns)

#Attempt 1 to clean the data

PROJECT = "/content/drive/MyDrive/MadridIntern"

conn = sqlite3.connect('fom_scheduler.db')

conn = sqlite3.connect("/content/drive/MyDrive/MadridIntern/fom_scheduler.db")

teacher.to_sql("availability", conn, if_exists="replace", index=False)
periods.to_sql("periods", conn, if_exists="replace", index=False)
counts.to_sql("courses", conn, if_exists="replace", index=False)
enrollment.to_sql("enrollment", conn, if_exists="replace", index=False)


conn.commit()
conn.close()